//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreMaterial.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ProductCategoryId { get; set; }
        public Nullable<int> ProductSubCategoryId { get; set; }
        public Nullable<bool> Sale { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> PriceSale { get; set; }
        public Nullable<int> ProductPhotoId { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Slide { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ProductPhoto ProductPhoto { get; set; }
        public virtual ProductSubCategory ProductSubCategory { get; set; }
    }
}
