//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreMaterial.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSubCategory
    {
        public ProductSubCategory()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int ProductSubcategoryId { get; set; }
        public string ProductSubcategoryName { get; set; }
        public Nullable<int> ProductCategoryId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
