//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreMaterial.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPhoto
    {
        public ProductPhoto()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int ProductPhotoId { get; set; }
        public string PhotoFileName { get; set; }
        public byte[] ThumbNailPhoto { get; set; }
        public byte[] LargePhoto { get; set; }
        public string LargePhotoFileName { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
